### ISSUE TITLE
ERROR   Unexpected exit {"err": "flag provided but not defined: <any command line flag>"}

### ISSUE THREAD

**Issue by aphex3k** [lightningequipment/circuitbreaker#41]
```
version: '3.7'

services:
        circuitbreaker:
                container_name: circuitbreaker
                image: ghcr.io/lightningequipment/circuitbreaker:latest
                restart: unless-stopped
                volumes:
                        - ${PWD}/circuitbreaker/data:/root/.circuitbreaker
                        - ${PWD}/app-data/lightning/data/lnd:/root/.lnd:ro
                networks:
                        default:
                                ipv4_address: 10.21.22.5
                command: [ "--rpcserver 10.21.21.9:10009", "--httplisten 0.0.0.0:9235" ]
                ports:
                       - "9235:9235"
```

I'm using the above docker-compose.yml but when I start the service I receive the following error:

```
circuitbreaker    | Incorrect Usage. flag provided but not defined: -rpcserver 10.21.21.9:10009
circuitbreaker    |
circuitbreaker    | NAME:
circuitbreaker    |    circuitbreakerd - A new cli application
circuitbreaker    |
circuitbreaker    | USAGE:
circuitbreaker    |    circuitbreaker [global options] command [command options] [arguments...]
circuitbreaker    |
circuitbreaker    | VERSION:
circuitbreaker    |    v0.4.0.
circuitbreaker    |
circuitbreaker    | COMMANDS:
circuitbreaker    |    help, h  Shows a list of commands or help for one command
circuitbreaker    |
circuitbreaker    | GLOBAL OPTIONS:
circuitbreaker    |    --rpcserver value          host:port of ln daemon (default: "localhost:10009")
circuitbreaker    |    --lnddir value             path to lnd's base directory (default: "/root/.lnd")
circuitbreaker    |    --tlscertpath value        path to TLS certificate (default: "/root/.lnd/tls.cert")
circuitbreaker    |    --network value, -n value  the network lnd is running on e.g. mainnet, testnet, etc. (default: "mainnet")
circuitbreaker    |    --macaroonpath value       path to macaroon file
circuitbreaker    |    --configdir value          path to CircuitBreaker's base directory (default: "/root/.circuitbreaker")
circuitbreaker    |    --listen value             grpc server listen address (default: "127.0.0.1:9234")
circuitbreaker    |    --httplisten value         http server listen address (default: "127.0.0.1:9235")
circuitbreaker    |    --stub                     set to enable stub mode (no lnd instance connected)
circuitbreaker    |    --help, -h                 show help
circuitbreaker    |    --version, -v              print the version
circuitbreaker    | 2023-01-25T18:40:09.549Z    ERROR   Unexpected exit {"err": "flag provided but not defined: -rpcserver 10.21.21.9:10009"}
circuitbreaker    | main.main
circuitbreaker    |     /src/main.go:139
circuitbreaker    | runtime.main
circuitbreaker    |     /usr/local/go/src/runtime/proc.go:250

```
